### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by gdborton** [pierrec/js-xxhash#19]
We're having issues with our npm-shrinkwrap.json file when installing `filru`, which ultimately depends on this lib. We think it's because the latest published version relies on `cuint@latest`. I see that this has been changed in master's package.json, but that a new version hasn't yet been published.

Would you mind publishing a patch for us?

cc: @ljharb

**Comment by ljharb** [comment]
fwiw this was fixed by #18, just never released (cc @kesne)

**Comment by pierrec** [comment]
Sorry I dropped the ball on this.
I have published a new version which includes the update.
Let me know if this is OK.

**Comment by ljharb** [comment]
Thank you!

**Comment by gdborton** [comment]
Thank you! Everything looks good now!
