### ISSUE TITLE
xxhash has no versions defined

### ISSUE THREAD

**Issue by krazyjakee** [pierrec/js-xxhash#7]
https://rails-assets.org/components/new

I wonder if it was something with the bower register process but I'm getting an error when trying to use xxhash on bower with rails-assets.

Any ideas?

**Comment by pierrec** [comment]
Sorry missed your question...
I am not sure, I dont know rails.

Have you tried simpy downloading from github and starting from there?

**Comment by mscdex** [comment]
It probably has to do with there being no tagged versions in git (GitHub shows 0 releases).

**Comment by pierrec** [comment]
Tag added as of v0.2.0.
