### ISSUE TITLE
xxhash64 support?

### ISSUE THREAD

**Issue by Pupix** [pierrec/js-xxhash#9]
Hello!

I was wondering if you are going to add 64bit support on your xxhash library. I've noticed that your cuint already support UINT64.

Cheers,
Pupix.

**Comment by pierrec** [comment]
Hello,

Yes that is something I am planning on doing as I have already updated the Go version but not the JS one yet.

**Comment by Pupix** [comment]
Glad to hear that. Will be waiting for an update then,

**Comment by pierrec** [comment]
I have added support for xxh64 in v0.2.0.
Please let me know of any issue.

**Comment by Pupix** [comment]
It's working great, thanks!
